spring:
  application:
    name: REHome-service
    version: 0.0.1
  datasource:
    url: jdbc:mysql://localhost:3306/REHome?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Kaguya-1210
    driver-class-name: com.mysql.cj.jdbc.Driver